FROM registry.cn-hangzhou.aliyuncs.com/biker/jira:1.0

#https://dev.aliyun.com/detail.html?spm=5176.1972343.2.6.edVM5M&repoId=14832
#docker run --d --p 8080:8080 registry.cn-hangzhou.aliyuncs.com/biker/jira:1.0
#Only open http://xxxx.xxx:8080 in browser !
